const mongoose = require("mongoose");

/**
 * The below things will be given by the user
 * - Job Description Schema - String
 * - Resume text - String
 * - Self description - String
 *
 * - matchScore - Number
 *
 * The below will be generated by the AI
 * - Technical Questions -> [{ question : "",
 *                             intention:"",
 *                             answer: "" }]
 * - Behavioural Questions -> [{ question : "",
 *                             intention:"",
 *                             answer: "" }]
 * - Skill gaps: [{ skill : "",
 *                  severity:"",
 *                  type: "" ,
 *                  enum: ["low", "medium", "                  high"]
 *               }]
 * - Preparation Plan : [{day : Number,
 *                  focus:String,
 *                  tasks: [String]
 */

// Sub Schema for Technical Questions
const technicalQuestionSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: [true, "Technical Question is required"],
    },
    intention: {
      type: String,
      required: [true, "Intention is required"],
    },
    answer: {
      type: String,
      required: [true, "Answer is required"],
    },
  },
  {
    _id: false,
  },
);

// Sub Schema for behavioural Questions
const behaviouralQuestionsSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: [true, "Technical Question is required"],
    },
    intention: {
      type: String,
      required: [true, "Intention is required"],
    },
    answer: {
      type: String,
      required: [true, "Answer is required"],
    },
  },
  {
    _id: false,
  },
);

// Sub Schema for Skill Gaps
const skillGapsSchema = new mongoose.Schema(
  {
    skill: {
      type: String,
      required: [true, "Skill is required"],
    },
    severity: {
      type: String,
      enum: ["low", "medium", "high"],
      required: [true, "Severity is required"],
    },
  },
  {
    _id: false,
  },
);

// Sub Schema for Preparation Plan
const preparationPlanSchema = new mongoose.Schema({
  day: {
    type: Number,
    required: [true, "Day is required"],
  },
  focus: {
    type: String,
    required: [true, "Focus is required"],
  },
  tasks: [
    {
      type: String,
      required: [true, "Task is required"],
    },
  ],
});

// Main Schema
const interviewReportSchema = new mongoose.Schema(
  {
    jobDescription: {
      type: String,
      required: [true, "Job Description is Required"],
    },
    resume: {
      type: String,
    },
    selfDescription: {
      type: String,
    },
    matchScore: {
      type: Number,
      min: 0,
      max: 100,
    },
    technicalQuestions: [technicalQuestionSchema],
    behaviouralQuestions: [behaviouralQuestionsSchema],
    skillGaps: [skillGapsSchema],
    preparationPlan: [preparationPlanSchema],
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users",
    },
    // title: {
    //   type: String,
    //   required: [true, "Job title is required"],
    // },
  },
  {
    timestamps: true,
  },
);

const interviewReportModel = mongoose.model(
  "InterviewReport",
  interviewReportSchema,
);

module.exports = interviewReportModel;
